import {
	CheckCircleOutlined as ActivateIcon,
	Add as AddIcon,
	CheckCircle as AllowEditingIcon,
	DoneOutlined as AllowIcon,
	Send as ApplyIcon,
	DoneAll as ApproveIcon,
	Apps as AppsIcon,
	Archive as ArchiveIcon,
	AdminPanelSettings as BASIcon,
	ArrowBack as BackIcon,
	Cancel as CancelIcon,
	ChevronLeft as ChevronLeftIcon,
	ChevronRight as ChevronRightIcon,
	Close as CloseIcon,
	Check as ConfirmIcon,
	Assignment as DCMIcon,
	DarkMode as DarkModeIcon,
	CancelOutlined as DeactivateIcon,
	Delete as DeleteIcon,
	DoubleArrow as DeployIcon,
	CancelOutlined as DisallowEditingIcon,
	CloseOutlined as DisallowIcon,
	Done as DoneIcon,
	Download as DownloadIcon,
	ContentCopy as DuplicateIcon,
	Edit as EditIcon,
	ExpandLess as ExpandLessIcon,
	ExpandMore as ExpandMoreIcon,
	DriveFileMove as ExportIcon,
	LocalAtm as FINIcon,
	AccountCircle as HRMIcon,
	Home as HomeIcon,
	Inventory as INVIcon,
	FileDownloadOutlined as ImportIcon,
	LightModeOutlined as LightModeIcon,
	Logout as LogoutIcon,
	Mail as MailIcon,
	Menu as MenuIcon,
	NotificationsActive as NotificationsActiveIcon,
	NotificationsNone as NotificationsNoneIcon,
	ShoppingCart as PURIcon,
	Percent as PercentIcon,
	Phone as PhoneIcon,
	Publish as PublishIcon,
	QuestionMark as QuestionMarkIcon,
	MonetizationOn as SNDIcon,
	Accessibility as SNMIcon,
	Save as SaveIcon,
	Search as SearchIcon,
	Settings as SettingsIcon,
	Upload as SubmitIcon,
	Sync as SyncIcon,
} from "@mui/icons-material";

export {
	ActivateIcon,
	AddIcon,
	AllowEditingIcon,
	AllowIcon,
	ApplyIcon,
	ApproveIcon,
	AppsIcon,
	ArchiveIcon,
	BASIcon,
	BackIcon,
	CancelIcon,
	ChevronLeftIcon,
	ChevronRightIcon,
	CloseIcon,
	ConfirmIcon,
	DCMIcon,
	DarkModeIcon,
	DeactivateIcon,
	DeleteIcon,
	DeployIcon,
	DisallowEditingIcon,
	DisallowIcon,
	DoneIcon,
	DownloadIcon,
	DuplicateIcon,
	EditIcon,
	ExpandLessIcon,
	ExpandMoreIcon,
	ExportIcon,
	FINIcon,
	HRMIcon,
	HomeIcon,
	INVIcon,
	ImportIcon,
	LightModeIcon,
	LogoutIcon,
	MailIcon,
	MenuIcon,
	NotificationsActiveIcon,
	NotificationsNoneIcon,
	PURIcon,
	PercentIcon,
	PhoneIcon,
	PublishIcon,
	QuestionMarkIcon,
	SNDIcon,
	SNMIcon,
	SaveIcon,
	SearchIcon,
	SettingsIcon,
	SubmitIcon,
	SyncIcon,
};
